# Generated by Django 4.0.4 on 2022-06-23 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombreCategoria', models.CharField(max_length=30, verbose_name='Nombre C')),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10, verbose_name='Rut del socio')),
                ('estado', models.CharField(max_length=1, verbose_name='Estado vigencia')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Codigo ')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre producto')),
                ('precio', models.CharField(max_length=15, verbose_name='Precio $')),
                ('stock', models.CharField(default='', max_length=25, verbose_name='Stock: ')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
